name: 'hello-world workflow'
on: 
  workflow_dispatch:
    inputs:
      NAME:
        description: 'name'
        default: 'neo'
        required: false
        type: string 


jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"

  hello_name:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{ github.event.inputs.NAME }}!"    