name: Cache demo
on: 
  workflow_dispatch:
    inputs:
      DOCKER_IMAGE:
        description: 'An image name passed from the caller workflow'
        default: 'saaverdo/flask:rc-a5f2e733'
        required: false
        type: string     
  pull_request:
    

env:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/cache@v3
        with:
          path: .m2/
          key: spring-${{ hashFiles('pom.xml') }}
      - run: mvn clean test 
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          report_paths: '**/TEST-*.xml'

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/cache@v3
        with:
          path: .m2/
          key: spring-${{ hashFiles('pom.xml') }}
      - run: mvn clean package
      - uses: actions/upload-artifact@v4
        with:
          name: demo-spring-artifact-dev
          path: target/*.jar

  package-test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: demo-spring-artifact
      - name: Display structure of downloaded files
        run: ls -R