name: 'hello-world workflow'
on: 
  workflow_dispatch:
    inputs:
      NAME:
        description: 'name'
        default: 'neo'
        required: false
        type: string 

  push:
    
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"

  hello-world-2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World 2!"

  hello_name:
    runs-on: ubuntu-latest
    needs: 
      - hello-world
    steps:
      - run: echo "Hello, ${{ github.event.inputs.NAME }}!"    
      
