name: 'jobs chain workflow'
on: 
  workflow_dispatch:
    inputs:
      NAME:
        description: 'name'
        default: 'neo'
        required: false
        type: string 
  push:

env:
  VAR_1: "val_1"
  VAR_2: "val_2"

jobs:
  hello-world:
    runs-on: local
    steps:
      - run: echo "Hello, World!"
      - run: echo "VAR1 - $VAR_1"
      - run: echo "env.VAR2 - ${{ env.VAR_2 }}"

  hello-world-2:
    runs-on: org
    env:
      VAR_2: "job_2"
      NAME: ${{ github.event.inputs.NAME }}
    steps:
      - run: |
          echo "Hello, World 2!"
          echo "VARS - $VAR_1, $VAR_2"
      - run: echo "env.VAR2 - ${{ env.VAR_2 }}"
      - name: List env vars
        run: env

  hello_name:
    runs-on: ec2
    needs: 
      - hello-world
      - hello-world-2
    steps:
      - run: echo "${{ toJSON(github) }}"
      - run: echo "Hello, ${{ inputs.NAME }}!"    

