name: Integration_test
on: 
  workflow_call:
    inputs:
      DOCKER_IMAGE:
        description: 'An image name passed from the caller workflow'
        default: 'saaverdo/flask:rc-a5f2e733'
        required: false
        type: string      

  workflow_dispatch:
    inputs:
      DOCKER_IMAGE:
        description: 'An image name passed from the caller workflow'
        default: 'saaverdo/flask:rc-a5f2e733'
        required: false
        type: string     


jobs:
  smoke-test:
    runs-on: ubuntu-latest
    # container: curlimages/curl
    services:
      db:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: superpass
          MYSQL_DATABASE: flask_db
          MYSQL_USER: admin
          MYSQL_PASSWORD: Pa55WD
        options: >-
          --health-cmd "healthcheck.sh --su-mysql --connect --innodb_initialized"
          --health-interval 20s
          --health-timeout 5s
          --health-retries 5      
        ports:
          - 3306:3306    
      appka:
        image: ${{ github.event.inputs.DOCKER_IMAGE }}
        env:
          FLASK_CONFIG: dev
        ports:
          - 8003:8000
    steps:
      - name: List containers
        run: docker ps
      - name: Check DB connection
        run: curl -o /dev/null -w "%{http_code}" http://127.0.0.1:8003
